config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'messages#index'
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates_presence_of :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @message = Message.new
    @messages = Message.all
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      flash.now[:alert] = @message.errors.full_messages.join(",")
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    -flash.each do |key, value|
      %p{class: "flash-#{key}"}= value
    = yield

app/views/messages/index.html.haml
.content
  .content-side
    =render partial: 'shared/side-menu'

  .content-main
    .chat-header.clearfix
      .chat-header--left
        %h2.group-name VRチーム
        %p.users
          Members: pchan

      .chat-header--right
        %a.edit-btn Edit

    .chat-body
      .chat-messages
        .chat-messages__message
          .chat-message__header.clearfix
            %p.chat-message__name 名前
            %p.chat-message__date 2016/12/1 00:00:00
          %p.chat-message__content メッセージ

    .chat-footer
      = form_for @message, url: messages_path do |f|
        .chat-footer__body
          =f.text_area :body, placeholder: 'Type a message', row: 1
          %label.chat-footer__file
            %i.fa.fa-picture-o{ area: {hidden: :true} }
          %input{ type: "submit", value: 'Send' }

app/views/shared/_side-menu.html.haml
.chat-user
  %h5.chat-user__name-title hikaru
  .chat-user__actions.clearfix
    %a.chat-user__actions__write
      %i.fa.fa-pencil-square-o
    %a.chat-user__actions__settings
      %i.fa.fa-cog

%ul.chat-groups
  %li.chat-group.clearfix
    %p.chat-group__name VR
    %p.chat-group__message unity